project/apps/front/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.views.generic import TemplateView

from apps.front.views.front import Mainpage, LawyerPage, ReviewsPage, TermsOfUse, About, LawyersListPage

app_name = 'front'

urlpatterns = [
    # Не менять порядок правил
    url(r'^$', Mainpage.as_view(), name='mainpage'),

    path('юристы/', LawyersListPage.as_view(), name='lawyers_list_page'),
    path('юристы/<int:page>/', LawyersListPage.as_view(), name='lawyers_list_page'),
    path('юристы/город/<city>-<int:city_id>/', LawyersListPage.as_view(), name='lawyers_list_page'),
    path('юристы/город/<city>-<int:city_id>/<int:page>/', LawyersListPage.as_view(), name='lawyers_list_page'),

    path('юрист/<int:id>/отзывы/', ReviewsPage.as_view(), name='lawyer_reviews'),
    path('юрист/<int:id>/отзывы/<int:page>/', ReviewsPage.as_view(), name='lawyer_reviews'),

    path('юрист/<int:id>/', LawyerPage.as_view(), name='lawyer_page'),

    path('отзывы/', ReviewsPage.as_view(), name='reviews_page'),
    path('отзывы/<int:page>/', ReviewsPage.as_view(), name='reviews_page'),

    path('пользовательское-соглашение/', TermsOfUse.as_view(), name='terms_of_use'),
    path('о-проекте/', About.as_view(), name='about'),
    path('новый-svem/', TemplateView.as_view(template_name='front/new_svem.html'), name='new_svem'),
    path('контакты/', TemplateView.as_view(template_name='front/contacts.html'), name='contacts'),

    # Все остальные url проверяем на редирект
    url(r'^', include('apps.front.urls_redirect_from_svem')),
]

project/apps/question/urls.py
from django.urls import path
from apps.question.views.front import ConfirmQuestion, QuestionDetail
app_name = 'question'

urlpatterns = [
    path('<int:pk>/', QuestionDetail.as_view(), name='detail'),
    path('<int:pk>/<slug:token>', ConfirmQuestion.as_view(), name='confirm_q'),
]

project/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
# from django.contrib.sitemaps import views as sitemap_views
from django.http import HttpResponseServerError
from django.urls import path, re_path
from django.contrib import admin, sitemaps
# from django.views.decorators.cache import cache_page
from django.utils.functional import curry
from django.views.defaults import page_not_found, permission_denied, server_error

from apps.mlo_auth.admin import LoginView
from apps.question.views.front import AskQuestion

handler403 = curry(permission_denied, template_name='403.html')
handler404 = curry(page_not_found, template_name='404.html')
handler500 = curry(server_error, template_name='500.html')

urlpatterns = [
    # url(r'^sitemap/', include('apps.sitemap.urls', namespace='sitemap')),
    # path('sitemap.xml', cache_page(86400)(sitemap_views.index), {'sitemaps': sitemaps}),
    path('задать-вопрос/', AskQuestion.as_view(), name='ask_question'),
    path('вопрос/', include('apps.question.urls', namespace='question')),
    path('вопросы/', include('apps.entry.urls.questions', namespace='questions')),
    path('личный-кабинет/', include('apps.account.urls', namespace='personal')),
    path('журнал/', include('apps.article.urls', namespace='article')),

    path('admin/login/', LoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),
    path('advice/', include('apps.advice.urls')),
    path('auth/', include('apps.svem_auth.urls')),
    path('api/', include('config.api_urls')),
    path('select2/', include('django_select2.urls')),

    # Остальные url обрабатываем в приложении front
    url(r'^', include('apps.front.urls', namespace='front')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

project/apps/review/models.py
import misaka
from django.db import models, connection
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from apps.entry.models import Entry
from apps.review.managers import ReviewManager, LikeManager
from config.settings import AUTH_USER_MODEL


class Likes(models.Model):
    """
    Лайки
    """
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE,
                              verbose_name=_('Ответ'))

    user = models.ForeignKey(AUTH_USER_MODEL, verbose_name=_('Пользователь'),
                             help_text=_('Пользователь, который поставил отметку'), on_delete=models.CASCADE)

    date = models.DateTimeField(_('Дата'), default=timezone.now)

    value = models.SmallIntegerField(_('Балл'))

    objects = LikeManager()

    class Meta:
        unique_together = ('entry', 'user')
        verbose_name = _('Отзыв')
        verbose_name_plural = _('Отзывы')

    @property
    def title_for_admin(self):
        return "Вопрос: %d" % (self.entry)

    def __str__(self):
        return "%d: %s (%d)" % (self.entry.pk, self.user.get_full_name, self.value)


class Review(models.Model):
    """
    Отзывы и комментарии к лайкам
    """
    like = models.OneToOneField(Likes, on_delete=models.CASCADE)
    review = models.TextField(_('Текст отзыва'))

    objects = ReviewManager()

    class Meta:
        ordering = ('-id', )
        verbose_name = _('Отзыв')
        verbose_name_plural = _('Отзывы')

    @property
    def html_review(self):
        """
        Возвращает текст отзыва форматированное в HTML.
        """
        return misaka.html(self.review)

    def __str__(self):
        return self.review

project/apps/review/views.py
from django.shortcuts import render

# Create your views here.

project/templates/review/generic/review_item.html
<article class="question-item">
    <div class="row">

        <div class="l-col subtitle pt-2 mb-3">{{ like.date|date:"j E Y" }}</div>

        <h5 class="r-col mb-0 mb-lg-3">
            <a href="{% url 'question:detail' like.entry.answer.on_question.pk %}"
            >{{ like.entry.answer.on_question.title|safe }}</a>
        </h5>

        <div class="l-col mb-3" style="margin-top: 2px;">
            {% if like.value > 0 %}
                <span class="d-lg-block text-danger">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </span>
            {% else %}
                <span class="d-lg-block text-danger">
                    <i class="icon-star"></i>
                    <i class="icon-star-empty text-light"></i>
                    <i class="icon-star-empty text-light"></i>
                    <i class="icon-star-empty text-light"></i>
                    <i class="icon-star-empty text-light"></i>
                </span>
            {% endif %}
            {# <span class="d-lg-block">№ { { like.entry.answer.on_question.pk } }</span> #}
            <span class="d-lg-block pl-1">{{ like.user.city.name }}</span>
        </div>

        <div class="r-col">
            <h6>{{ like.user.get_name }}</h6>
            <p>{% if like.review %}{{ like.review|safe }}{% else %}
                {{ like.user.get_name }}, остался{% if like.value < 0 %} не{% endif %} доволен ответом юриста.
            {% endif %}</p>
            <!--p class="text-muted">За ответ юриста
                <a class="text-muted " href="{% url "front:lawyer_page" like.entry.author.pk %}">{{ like.entry.author }}</a>
            </p-->
        </div>

    </div>
    <hr class="mb-4">
</article>