project/apps/account/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from apps.account.views import InfoEdit, UserEdit, ContactEdit, EducationEdit, ExperienceEdit, AdviceSchedulerEdit, \
    SubscriptionEdit

app_name = 'account'

urlpatterns = [
    path(
        'вопросы/',
        include('apps.entry.urls.personal_questions', namespace='personal_questions')
    ),

    path(
        'редактировать-профиль/',
        login_required(login_url='/auth/login/')(InfoEdit.as_view(template_name='account/edit/additional.html')),
        name='edit_profile'
    ),

    path(
        'регистрационные-данные/',
        login_required(login_url='/auth/login/')(UserEdit.as_view(template_name='account/edit/main.html')),
        name='edit_user_data'
    ),

    path(
        'образование/',
        login_required(login_url='/auth/login/')(EducationEdit.as_view(template_name='account/edit/education.html')),
        name='edit_education'
    ),

    path(
        'опыт-работы/',
        login_required(login_url='/auth/login/')(ExperienceEdit.as_view(template_name='account/edit/experience.html')),
        name='edit_experience'
    ),

    path(
        'контакты/',
        login_required(login_url='/auth/login/')(ContactEdit.as_view(template_name='account/edit/contact.html')),
        name='edit_contact'
    ),

    path(
        'платные-заявки/',
        login_required(login_url='/auth/login/')(AdviceSchedulerEdit.as_view(template_name='account/edit/scheduler.html')),
        name='edit_scheduler'
    ),

    path(
        'уведомления/',
        login_required(login_url='/auth/login/')(SubscriptionEdit.as_view(template_name='account/edit/subscription.html')),
        name='edit_subscription'
    ),
]

project/apps/front/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.views.generic import TemplateView

from apps.front.views.front import Mainpage, LawyerPage, ReviewsPage, TermsOfUse, About, LawyersListPage

app_name = 'front'

urlpatterns = [
    # Не менять порядок правил
    url(r'^$', Mainpage.as_view(), name='mainpage'),

    path('юристы/', LawyersListPage.as_view(), name='lawyers_list_page'),
    path('юристы/<int:page>/', LawyersListPage.as_view(), name='lawyers_list_page'),
    path('юристы/город/<city>-<int:city_id>/', LawyersListPage.as_view(), name='lawyers_list_page'),
    path('юристы/город/<city>-<int:city_id>/<int:page>/', LawyersListPage.as_view(), name='lawyers_list_page'),

    path('юрист/<int:id>/отзывы/', ReviewsPage.as_view(), name='lawyer_reviews'),
    path('юрист/<int:id>/отзывы/<int:page>/', ReviewsPage.as_view(), name='lawyer_reviews'),

    path('юрист/<int:id>/', LawyerPage.as_view(), name='lawyer_page'),

    path('отзывы/', ReviewsPage.as_view(), name='reviews_page'),
    path('отзывы/<int:page>/', ReviewsPage.as_view(), name='reviews_page'),

    path('пользовательское-соглашение/', TermsOfUse.as_view(), name='terms_of_use'),
    path('о-проекте/', About.as_view(), name='about'),
    path('новый-svem/', TemplateView.as_view(template_name='front/new_svem.html'), name='new_svem'),
    path('контакты/', TemplateView.as_view(template_name='front/contacts.html'), name='contacts'),

    # Все остальные url проверяем на редирект
    url(r'^', include('apps.front.urls_redirect_from_svem')),
]

project/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
# from django.contrib.sitemaps import views as sitemap_views
from django.http import HttpResponseServerError
from django.urls import path, re_path
from django.contrib import admin, sitemaps
# from django.views.decorators.cache import cache_page
from django.utils.functional import curry
from django.views.defaults import page_not_found, permission_denied, server_error

from apps.mlo_auth.admin import LoginView
from apps.question.views.front import AskQuestion

handler403 = curry(permission_denied, template_name='403.html')
handler404 = curry(page_not_found, template_name='404.html')
handler500 = curry(server_error, template_name='500.html')

urlpatterns = [
    # url(r'^sitemap/', include('apps.sitemap.urls', namespace='sitemap')),
    # path('sitemap.xml', cache_page(86400)(sitemap_views.index), {'sitemaps': sitemaps}),
    path('задать-вопрос/', AskQuestion.as_view(), name='ask_question'),
    path('вопрос/', include('apps.question.urls', namespace='question')),
    path('вопросы/', include('apps.entry.urls.questions', namespace='questions')),
    path('личный-кабинет/', include('apps.account.urls', namespace='personal')),
    path('журнал/', include('apps.article.urls', namespace='article')),

    path('admin/login/', LoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),
    path('advice/', include('apps.advice.urls')),
    path('auth/', include('apps.svem_auth.urls')),
    path('api/', include('config.api_urls')),
    path('select2/', include('django_select2.urls')),

    # Остальные url обрабатываем в приложении front
    url(r'^', include('apps.front.urls', namespace='front')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

project/apps/front/models.py
from django.db import models
from image_cropping import ImageCropField, ImageRatioField

from apps.sxgeo.models import Cities


class CityMeta(models.Model):

    city = models.ForeignKey(Cities, on_delete=models.NOT_PROVIDED)

    lawyers_page_description = models.TextField(
        "Описание для списка юристов из города",
        null=True,
        default=None,
    )

    lawyers_page_cover_orig = ImageCropField(blank=True, upload_to='front/city_meta/%Y/%m/')
    lawyers_page_cover = ImageRatioField('lawyers_page_cover_orig', '1920x500', verbose_name="Обложка")

project/apps/advice/views/front.py
import hashlib

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.utils.datastructures import MultiValueDictKeyError
from django.views.decorators.csrf import csrf_exempt

from apps.advice.models import Advice
from apps.entry.models import Question
from config.settings import MONEY_YANDEX_SECRET


@csrf_exempt
def advice_to_payment_confirmed(request):
    """
    http://мойюрист.онлайн/advice/to_payment_confirmed — url подтверждения
    ?operation_id=904035776918098009&notification_type=p2p-incoming&datetime=2014-04-28T16:31:28Z&sha1_hash=8cd2341395aa45f4bfe1f5d5079b878949d3e3cc&sender=41003188981230&codepro=false&currency=643&amount=800.00&withdraw_amount=800.00&label=advice.1500026
    8cd2341395aa45f4bfe1f5d5079b878949d3e3cc
    """

    import sys
    sys.stdout = open('/tmp/payment.log', 'a')
    print(timezone.now())
    print(request.POST)

    resp = ''
    # data = request.GET
    data = request.POST

    if not request.POST:
        return HttpResponse('Нет данных')

    try:
        result_string = "&".join((
            data['notification_type'],
            data['operation_id'],
            data['amount'],
            data['currency'],
            data['datetime'],
            data['sender'],
            data['codepro'],
            MONEY_YANDEX_SECRET,
            data['label']
        ))
    except MultiValueDictKeyError:
        return HttpResponse('Неверные данные')

    sha = hashlib.sha1(result_string.encode()).hexdigest()
    # print(sha)

    if sha == data['sha1_hash']:

        # Пример label=advice.456456
        label = data['label'].split('.')[0]

        if label == 'advice':
            question_id = data['label'].split('.')[1]
            question = get_object_or_404(Question, pk=question_id)
            question.pay()
            advice = Advice.objects.get(question_id=question_id)

            if advice.to_payment_confirmed():
                # Обновляем цену оплаченную по факту
                if 'withdraw_amount' in data:
                    advice.cost = int(float(data['withdraw_amount']))
                    advice.save(update_fields=['cost'])

                resp = 'Платёж подтверждён, вопрос: {}'.format(question_id)
            else:
                resp = 'Не удалось обновить статус завки'

    else:
        resp = 'Хеш неверен! Проверьте секретное слово'

    print(resp)
    print('----------------------------------------------')
    sys.stdout.close()

    return HttpResponse(resp)

project/apps/front/views/api.py
from apps.svem_system.views.api import ApiView
from django.conf import settings
from django.urls import reverse


class FrontDefault(ApiView):
    @classmethod
    def get(cls, request):
        return {
            'settings': {
                'advice_cost':  settings.ADVICE_COST,
                'answers_expand': settings.ANSWERS_TREE_IS_EXPANDED,
                'site_url': settings.SITE_URL,
                'site_protocol': settings.SITE_PROTOCOL

            },
            'advice': {
                'money_yandex_purse': settings.MONEY_YANDEX_PURSE,
                'payment_form_title': settings.PAYMENT_FORM_TITLE,
                'payment_form_target': settings.PAYMENT_FORM_TARGET,
                'advice_cost': settings.ADVICE_COST,
            },
            'urls': {
                'show_question': reverse('question:detail', kwargs={'pk': 0}),
                'ask_question': reverse('ask_question'),
            }
        }

project/apps/front/views/front.py
import pymorphy2
from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponseServerError
from django.views.generic import TemplateView, ListView

from apps.entry.models import Question
from apps.front.models import CityMeta
from apps.rating.models import Rating
from apps.review.models import Review, Likes
from apps.sxgeo.models import Cities


class Mainpage(TemplateView):
    template_name = 'front/index.html'

    def get_context_data(self, **kwargs):
        context = super(Mainpage, self).get_context_data(**kwargs)
        context['h1'] = "Консультация юриста онлайн"

        context['questions'] = Question.published.filter(reply_count__gt=0).order_by('-pk')[:5]
        context['lawyers'] = Rating.lawyers.filter(month_rate__gt=0)[:15]
        context['reviews'] = Review.objects.filter(like__value__gt=0)[:8]

        return context


class LawyerPage(TemplateView):
    template_name = 'front/lawyer_page.html'

    def get_context_data(self, **kwargs):
        context = super(LawyerPage, self).get_context_data(**kwargs)

        try:
            lawyer = get_user_model().objects.get(pk=kwargs['id'], role__gt=1, is_active=True)
        except ObjectDoesNotExist:
            raise Http404

        questions = Question.published.search('', 0, 10, {'answers_authors_id': (lawyer.pk,)})

        context.update({
            'likes': Likes.objects.filter(entry__author=lawyer, user__role=1).order_by("-date")[:10],
            'lawyer': lawyer,
            'questions': questions,
            'questions_count': questions.count,
        })

        return context


class LawyersListPage(ListView):
    template_name = 'front/lawyers_list_page.html'
    context_object_name = 'lawyers_list'
    paginate_by = 10
    paginate_orphans = 4

    def get_queryset(self):
        qs = get_user_model().objects.\
            filter(role=2, is_active=True).\
            order_by('-rating__month_rate', '-info__answer_count')

        if 'city_id' in self.kwargs:
            qs = qs.filter(city_id=self.kwargs['city_id'])

        return qs

    def get_context_data(self, **kwargs):
        context = super(LawyersListPage, self).get_context_data(**kwargs)

        title = 'Юристы и адвокаты. Юридическая помощь и консультации на Мойюрист.онлайн'
        h1 = 'Юристы и адвокаты'

        if 'city_id' in self.kwargs:
            if self.kwargs['city_id'] == 520555:
                city_name = 'Нижнего Новгорода'
            elif self.kwargs['city_id'] == 501175:
                city_name = 'Ростова-на-Дону'
            else:
                city = Cities.objects.get(pk=self.kwargs['city_id'])
                morph = pymorphy2.MorphAnalyzer()
                c = morph.parse(city.name_ru)[0]
                city_name = c.inflect({'gent'}).word.title()

            try:
                city_meta = CityMeta.objects.get(city_id=self.kwargs['city_id'])
                context.update({
                    'city_meta': city_meta,
                })
            except CityMeta.DoesNotExist:
                pass

            title = 'Юристы и адвокаты {}. Юридическая помощь и консультации на Мойюрист.онлайн'.format(city_name)
            h1 = 'Юристы и адвокаты {}'.format(city_name)

            context.update({
                'city_id': self.kwargs['city_id'],
                'city': city_name,
            })

        context.update({
            'title': title,
            'h1': h1,
        })

        return context


class ReviewsPage(ListView):
    template_name = 'front/reviews_page.html'
    context_object_name = 'likes'
    paginate_by = 15
    paginate_orphans = 5

    def get_queryset(self):
        qs = Likes.objects.filter(user__role=1).order_by("-date")

        if 'id' in self.kwargs:
            return qs.filter(entry__author_id=self.kwargs['id'])

        return qs

    def get_context_data(self, **kwargs):
        context = super(ReviewsPage, self).get_context_data(**kwargs)
        lawyer = False
        # Отзывы юриста
        if 'id' in self.kwargs:
            try:
                lawyer = get_user_model().objects.get(pk=self.kwargs['id'], role__gt=1)
            except ObjectDoesNotExist:
                raise Http404
        context.update({
            'lawyer': lawyer,
            'like_positive_count': self.get_queryset().filter(value__gt=0).count(),
            'like_negative_count': self.get_queryset().filter(value__lt=0).count(),
        })
        return context


class TermsOfUse(TemplateView):
    template_name = 'front/terms_of_use.html'


class About(TemplateView):
    template_name = 'front/about.html'

project/apps/front/views/redirect_from_svem.py
from django.http import HttpResponse, Http404
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import RedirectView

from apps.entry.models import Question, Tag
from apps.rubric.models import Rubric


def question(request, **kwargs):
    q = get_object_or_404(Question, pk=kwargs['question_id'])
    return redirect(q, permanent=True)


def tag(request, **kwargs):
    q = get_object_or_404(Tag, pk=kwargs['tag_id'])

    try:
        r = Rubric.objects.get(slug=q.slug)
    except Rubric.DoesNotExist:
        if 'page' in kwargs:
            return redirect('questions:list_tag', permanent=True, tag=q.slug, page=kwargs['page'])
        else:
            return redirect('questions:list_tag', permanent=True, tag=q.slug)
    return redirect('questions:list_rubric', permanent=True, rubric_slug=r.slug)


def rubric(request, **kwargs):

    slug2 = kwargs['rubric_slug2']
    if slug2 == 'Drugie-voprosy':
        slug2 = 'Prochie-voprosy'

    if slug2 == 'Pensii':
        slug2 = 'Pensii-i-socobespechenie'

    if slug2 == 'Migracionnye-voprosy':
        pass

    try:
        r = Rubric.objects.get(slug2=slug2)
    except:
        return redirect('questions:list')

    if 'page' in kwargs:
        return redirect('questions:list_rubric', permanent=True, rubric_slug=r.slug, page=kwargs['page'])
    else:
        return redirect('questions:list_rubric', permanent=True, rubric_slug=r.slug)


def questions(request, **kwargs):
    if 'page' in kwargs:
        return redirect('questions:list', permanent=True, page=kwargs['page'])
    else:
        return redirect('questions:list', permanent=True)


def user(request, **kwargs):
    return redirect('front:lawyer_page', permanent=True, id=kwargs['id'])


def review(request, **kwargs):
    if 'page' in kwargs:
        return redirect('front:reviews_page', permanent=True, page=kwargs['page'])
    else:
        return redirect('front:reviews_page', permanent=True)


def blog(request, **kwargs):

    if kwargs['slug'] == 'likbez':
        slug = 'юридический-ликбез'
    elif kwargs['slug'] == 'publication':
        slug = 'публикации'
    else:
        raise Http404("Article dir doesn't exists")

    return redirect(
        'article:article',
        permanent=True,
        slug=slug,
        id=str(int(kwargs['id'])+600000),
    )

project/templates/front/generic/counters.html
<!--LiveInternet counter--><script type="text/javascript">
new Image().src = "//counter.yadro.ru/hit?r"+escape(document.referrer)+((typeof(screen)=="undefined")?"":";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+";h"+escape(document.title.substring(0,150))+";"+Math.random();</script>
<!--/LiveInternet-->
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter38190105 = new Ya.Metrika({ id:38190105, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script>
<noscript><div><img src="https://mc.yandex.ru/watch/38190105" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-3708167-3"></script>
<script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'UA-3708167-3');</script>

project/templates/front/generic/footer.html
<footer class="main-footer">
    <div>
        <div class="ttl">
            <a href="{% url 'front:terms_of_use' %}">Пользовательсткое соглашение</a><br>
            <div>Техническая поддержка: <a href="mailto:support@мойюрист.онлайн">support@мойюрист.онлайн</a></div>
            <!--a href="#">Карта сайта</a-->
        </div>
        <div class="mdd">
            <a href="https://vk.com/moiyurist.online"><span class="icon-vk"></span></a>
            <a href="https://fb.com/moiyurist.online"><span class="icon-fb"></span></a>
            <a href="https://twitter.com/moiyurist.online"><span class="icon-tw"></span></a>
        </div>
        <div class="cpr">© Мойюрист.онлайн — юридическая помощь в любое время, 2005–2018.
            <nobr>Дизайн — <a href="http://mortis.ru" rel="nofollow">mortis.ru</a></nobr>
        </div>
    </div>
</footer>

project/templates/front/generic/lawyer_card.html
{% load cropping %}
{% load number %}

<div class="lawyer-card">
    <div class="lanyard"></div>
    <img src="{% include 'account/generic/photo.html' with item=item.user %}" alt="{{ item.user }}"/>
    <div class="lawyer-card-title">
        <h6><a href="{% url 'front:lawyer_page' item.user.pk %}">{{ item.user }}</a></h6>
        <p class="rating">{{ item.get_rate }}</p>
    </div>
    <div class="lawyer-card-body d-flex flex-column justify-content-between">
        <div>
            <h6>{{ item.user.info.title|default:item.user.get_role_display }}</h6>
            <p>{{ item.user.info.short }}</p>
        </div>
        <div class="lawyer-card-body_review d-flex align-items-center justify-content-between">
            <span class="text-danger">
                <i class="icon-star mr-1"></i><i class="icon-star mr-1"></i><i class="icon-star mr-1"></i><i class="icon-star mr-1"></i><i
                    class="icon-star mr-1"></i>
            </span>
            <a class="text-muted small" href="{% url 'front:lawyer_reviews' item.user.pk %}">
                {{ item.user.info.review_count|number:'отзыв|отзыва|отзывов' }}
            </a>
        </div>
    </div>
</div>

project/templates/front/generic/lawyer_header.html
{#  Header #}
<section class="blue lawyer-page_header">
    <div class="lawyer-page_container">
        <div class="row align-items-end">
            <div class="lawyer-page_header_l-col">
                <div class="photo">
                    <img src="{% include 'account/generic/photo.html' with item=lawyer %}" alt="lawyer">
                </div>
            </div>
            <div class="lawyer-page_header_r-col">
                <h1>{{ lawyer.get_full_name }}</h1>
                <div class="lead">{{ lawyer.info.short|default:lawyer.get_role_display }}<br>
                    <small>{{ lawyer.city.name }}</small>
                </div>
                <a class="btn btn-sm btn-white" href="{% url "ask_question" %}">Задать вопрос <i
                        class="icon-message_bubble ml-2"></i></a>
            </div>
        </div>
    </div>
</section>

project/templates/front/generic/navbar.html
{% load static %}

<nav class="mlo-navbar">

    <a class="mlo-navbar_brand" href="/">
        <img src="{% static "/img/nav/logo.svg" %}">
    </a>

    {% block navbar_title %}
        <div class="mlo-navbar_title">

            {% if user.hot_line_phone %}
                <span class="tg">консультация юриста</span>
                <span class="t">{{ user.hot_line_phone }}</span>
                <span class="g">консультация юриста</span>
            {% else %}
                <span class="tg">Консультация юриста онлайн</span>
                <span class="g">Консультация юриста онлайн</span>
            {% endif %}
            {% if  user.location.loc_id > 0 %}<span class="c">в {{ user.location.loc_name_loct }}</span>{% endif %}

        </div>
    {% endblock %}

    <div class="mlo-navbar_actions">
        {% if user.role == 2 %}
            <a href="{% url 'questions:list' %}" class="action_item d-none d-sm-inline-flex">Отвечать</a>
        {% else %}
            <a href="{% url 'ask_question' %}" class="action_item d-none d-sm-inline-flex">Задать вопрос юристу</a>
        {% endif %}
        <!--a href="#" class="fix-navbar sq -active"><span class="icon-lightning"></span></a-->
        {% if user.is_authenticated and user.role > 0 %}
            <a href="{% url 'personal:edit_profile' %}" class="action_item sq">
                <img src="{% include 'account/generic/pic.html' with item=user %}">
            </a>
        {% endif %}

        <a href="#" class="action_item slide-menu-toggle sq"></a>
    </div>

    {% block navbar_addbar %}{% endblock %}

</nav>

project/templates/front/generic/slidemenu.html
<div class="slide-menu">

    <div class="mt-4">
        <ul>
            {% if user.is_authenticated and user.role == 2 %}
                <li><a href="{% url 'personal:edit_profile' %}" class="font-weight-semibold">Личный кабинет</a></li>
                <li><a href="{% url 'questions:list' %}">Отвечать на вопросы</a></li>
            {% else %}
                <li><a href="{% url 'ask_question' %}">Задать вопрос юристу</a></li>
                {% if user.is_authenticated and user.role == 1 %}
                    <li><a href="{% url 'questions:list' %}?my">Мои вопросы</a></li>
                {% endif %}
                <!--li><a href="#">Как это работает?</a></li-->
                <li><a href="{% url 'questions:list' %}">Вопросы и ответы</a></li>
                <!--li><a href="#">Наши юристы</a></li-->
            {% endif %}
            <li><a href="{% url 'front:lawyers_list_page' %}">Наши юристы</a></li>
            <li><a href="{% url 'front:reviews_page' %}">Отзывы</a></li>
            <li><a href="{% url 'front:contacts' %}">Контакты</a></li>
            <li><a href="{% url 'front:about' %}">О проекте</a></li>
        </ul>
        {% comment %}<div class="text-muted">У Svem.ru новый дизайн и домен! <a href="{% url 'front:new_svem' %}">Подробнее…</a></div>{% endcomment %}
    </div>

    <footer>
        {% if user.is_authenticated %}
            <p><a href="/auth/logout/" class="btn btn-outline-primary btn-sm">Выйти
                <i class="icon-nav-arrow-right ml-1"></i></a></p>
            <p class="text">Вы авторизованы как {{ user.get_full_name }}</p>
        {% else %}
            <p>
                <a href="/auth/login/?next={{ request.get_full_path }}" class="btn btn-outline-primary btn-sm">Вход<i class="icon-person ml-2"></i></a>
            </p>
            <p class="text">или <a class="text-dark" href="/auth/registration/">Зарегистрируйтесь</a> на
                сайте юридической помощи «Мойюрист.онлайн»</p>
        {% endif %}
    </footer>

</div>

project/templates/front/generic/yandex-share.html
<script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
<script src="//yastatic.net/share2/share.js"></script>
<div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,moimir,gplus,twitter" data-counter=""></div>